name: Deploy to VPS

on:
  push:
    branches:
      - main  # деплой при пуше в main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настраиваем SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 91.205.220.47 >> ~/.ssh/known_hosts

      # 3. Подключаемся к VPS и выполняем деплой
      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 deploy-backend@91.205.220.47 << 'EOF'
            # создаём директорию, если её нет
            mkdir -p /home/deploy-backend/myapp
            cd /home/deploy-backend/myapp

            # если .git нет, клонируем
            if [ ! -d ".git" ]; then
              git clone https://github.com/DinarSharipov/open_router_bot_backend.git .
            else
              git pull origin main
            fi

            # запускаем Docker Compose
            docker compose down
            docker compose up -d --build
          EOF
